### ISSUE TITLE
Crash on real device with arm

### ISSUE THREAD

**Issue by mironoff2007** [InsanusMokrassar/AndroidExposedTutorial#2]
Crash on real device with arm. X86 emulator works fine.
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.text-y0ZqgH1vwIgRDVtkTETz7g==/base.apk"],nativeLibraryDirectories=[/data/app/app.text-y0ZqgH1vwIgRDVtkTETz7g==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsqlitejdbc.so"

Organize libs folder according to https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#how-to-use-with-android

 Pull request -https://github.com/InsanusMokrassar/AndroidExposedTutorial/pull/1

**Comment by InsanusMokrassar** [comment]
Hello and sorry for that long delay. I did several things, but in context of your task It was enough to rename `arm` to `armeabi` and `aarch64` to `arm64-v8a`. See [this](https://github.com/InsanusMokrassar/AndroidExposedTutorial/commit/9e202d2efd1639a9025d4a31266ae44af8c72525) commit for more info
